### ISSUE TITLE
Excuse me, where is the data of the yaml file exported, and how can I achieve this hand movement?

### ISSUE THREAD

**Issue by baixinping618** [RimoChan/Vtuber_Tutorial#11]
0

**Comment by RimoChan** [comment]
Excuse me, English is muzukashi desu!

**Comment by baixinping618** [comment]
请问，导出的yaml文件的数据在哪里，这个手部动作怎么实现？

**Comment by Nova-Noir** [comment]
> Excuse me, English is muzukashi desu!

蚌埠住了

**Comment by RimoChan** [comment]
> 请问，导出的yaml文件的数据在哪里，这个手部动作怎么实现？

我还是不太明白，导出yaml文件的数据和手部动作指的是什么？
实例代码里面有「信息.yaml」，然后手部动作我没有提到过……

**Comment by baixinping618** [comment]
就是我想问一下   我需要怎么样才能让这个psd模型人物的手部也可以挥舞起来

**Comment by baixinping618** [comment]
可以给个联系方式交流一下吗

**Comment by baixinping618** [comment]
你的「信息.yaml」是怎么得到的呢
