### ISSUE TITLE
Unable to load numpy_formathandler accelerator from OpenGL_accelerate

### ISSUE THREAD

**Issue by NetherXiaoYu** [RimoChan/Vtuber_Tutorial#2]
作者晓得这个是怎么肥事嘛，百度搜出来一堆英文没一个能解决的。。

**Comment by RimoChan** [comment]
我记得这东西不用装，你把它直接卸载了就好了……

**Comment by NetherXiaoYu** [comment]
我觉得可能是32位的问题，现在换64位看看。。

**Comment by NetherXiaoYu** [comment]
换64位之后没问题了，time.clock()貌似在Python3.8版本不行了，改为time.perf_counter()才能正常运行
